# Generated by Django 5.0.2 on 2024-03-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_pharamcy_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pharmacyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.pharamcy'),
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('pharmacyID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.pharamcy')),
            ],
        ),
    ]
