# Generated by Django 5.0.2 on 2024-03-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_doctor_pharmacyid_pharmacist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refound_amount', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('refound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.refound')),
            ],
        ),
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('Pharamcy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.pharamcy')),
                ('doctorID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor')),
                ('Reception_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.reception')),
                ('refound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.refound')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=15)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_amount', models.CharField(max_length=20)),
                ('doctorID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor')),
                ('patientID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('refound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.refound')),
            ],
        ),
    ]
